version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: woofer
    container_name: woofer-app
    command: npm run start
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local