version: '3.4'

services:

  ##############################################################################
  # React app
  ##############################################################################

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    image: spencerlepine/mern-ec2-client
    restart: always
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app

  ##############################################################################
  # Nodejs backend
  ##############################################################################

  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    image: spencerlepine/mern-ec2-server
    restart: always
    container_name: 'backend'
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - /usr/src/nodejs/node_modules
      - ./server:/usr/src/nodejs