version: '3.9'

services:
  nodeserver:
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
        - 3000:3000
    volumes:
        - /app/node_modules
        - ./:/app
    # image: spencerlepine/woofer
    restart: always

  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    ports:
        - 80:80
    # image: spencerlepine/woofer-nginx
    restart: always

