# docker-compose.yml in root directory
# 3 seperate Dockerfiles, in client/, server/, and nginx
# 2 seperate package.json in client/ and server/

version: '3.9'

services:
  backend:
    build:
        context: ./server
        dockerfile: Dockerfile
    volumes:
        - /app/node_modules
        - ./server:/app
    restart: always

  frontend:
    build:
        context: ./client
        dockerfile: Dockerfile
    volumes:
        - /app/node_modules
        - ./client:/app

  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    ports:
        - 3000:80
    restart: always