export const HOME = "/"
export const LOGIN = "/login"
export const SIGNUP = "/signup"
export const WELCOME = "/welcome"
export const SETTINGS = "/settings"
export const PROFILE = "/profile"
export const CHATS = "/chats"
