export const mockUser = {
  uid: "asdf123456",
  emailVerified: true,
  userId: "1234asdfuasdf",
  email: "johndoe@gmail.com",
  username: "john124412",
  firstName: "John",
  lastName: "Doe",
  profilePicture:
    "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
  zodiac: "Virgo",
  gender: "Male",
  breed: "Shiba",
  bio: "Example description",
  birthday: "06/12/2002",
  preference: "Female",
  zipcodes: [],
  pictures: [],
  chats: [],
}

export const mockUserB = {
  uid: "jd82ndkv14",
  emailVerified: true,
  userId: "jd82ndkv14",
  email: "pippapaw@gmail.com",
  username: "pippa124412",
  firstName: "Pippa",
  lastName: "Bonzai",
  profilePicture:
    "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
  zodiac: "Cancer",
  gender: "Female",
  breed: "Shiba",
  bio: "Example description",
  birthday: "06/12/2001",
  preference: "Female",
  zipcodes: [],
  pictures: [],
  chats: [],
}
