name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  test-client:
    uses: ./.github/workflows/test.yml
    secrets:
      SUB_FOLDER: ${{ secrets.SUB_FOLDER_CLIENT }}

  test-server:
    needs: [test-client]
    uses: ./.github/workflows/test.yml
    secrets:
      SUB_FOLDER: ${{ secrets.SUB_FOLDER_SERVER }}

  build:
    needs: [test-server]
    uses: ./.github/workflows/build.yml