name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  test:
    uses: ./.github/workflows/test.yml

  deploy-dev:
    needs: [test]
    uses: ./.github/workflows/deploy.yml