name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: [test]
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }} ## TODO: _DEV

  # TODO, remove this, just deploy for practice
  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}