name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  test:
    uses: ./.github/workflows/test.yml

  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      DOCKER_USERNANE: spencerlepine
      DOCKER_REPO: woofer-dev
