name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: [test]
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO_DEV }}

  # TODO, remove this, just deploy for practice
  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets:
      EC2_REMOTE_HOST: ${{ secerets.EC2_REMOTE_HOST }}
      EC2_REMOTE_USER: ${{ secerets.EC2_REMOTE_USER }}
      EC2_SSH_KEY: ${{ secerets.EC2_SSH_KEY }}
      EC2_PASSPHRASE: ${{ secerets.EC2_PASSPHRASE }}
      EC2_PORT: ${{ secerets.EC2_PORT }}
      DOCKER_CONTAINER_NAME: ${{ secerets.DOCKER_CONTAINER_NAME }}
      DOCKER_HUB_REPO: ${{ secerets.DOCKER_HUB_REPO }}