name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  test-client:
    uses: ./.github/workflows/test.yml
    secrets:
      FOLDER: client

  test-server:
    uses: ./.github/workflows/test.yml
    secrets:
      FOLDER: server

  build:
    needs: [test-server]
    uses: ./.github/workflows/build.yml