name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  # test:
  #   uses: ./.github/workflows/test.yml

  build:
    # needs: [test]
    uses: ./.github/workflows/build.yml
