name: branch_check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  test:
    uses: ./.github/workflows/test.yml

  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    env:
      docker_username: spencerlepine
      docker_repo: woofer-dev
