name: Continuous Integration

on:
  workflow_call:

jobs:

  node_ci:
    name: Node CI
    uses: ./.github/workflows/node_ci.yml

  docker_ci:
    name: Docker CI
    uses: ./.github/workflows/docker_ci.yml